version: '3'
services:
  redis-server:
    image: 'redis'
  node-redis1:
    restart: on-failure # no, always, on-failure, unless-stopped
    build: .
    ports:
      - "7001:8081"
  node-redis2:
    build: .
    ports:
      - "7002:8081"